### ISSUE TITLE
Prevent adding user to users if it has already logged in

### ISSUE THREAD

**Issue by JasonJunJun** [JMPerez/c#11]
Is this a good idea? Want to know what you think about it.
![multiple_mes](https://user-images.githubusercontent.com/13383097/53738348-edc57480-3ec9-11e9-9642-2e2fc2a26ae8.png)

**Comment by JMPerez** [comment]
Yes, that's a great idea. The same user should only appear once in the list.

**Comment by JasonJunJun** [comment]
What does the below comment mean? I don't fully understand, hope you can explain it.  😂
https://github.com/JMPerez/c/blob/a04f9d7280025a534e81dad10c64ac9c6cd39c0c/server/api.js#L153
