### ISSUE TITLE
Cant hear the playing song

### ISSUE THREAD

**Issue by abbrechen** [JMPerez/c#14]
Cool app btw. but if I add a song to the queue I cant hear anything. My bluetooth connected headphones are connected well because I can listen to other web apps.

**Comment by JasonJunJun** [comment]
Maybe it's better to provide some more detail. I guess the reason is that you connect to a device which is not the active one.

**Comment by abbrechen** [comment]
I followed your advice on the README and setup the config tokens and the callback in the Spotify Dev Dashboard. After it I logged into C and added some songs. But Chrome doesnt even show the C-tab is playing sound (normally the tab has a volume icon then). My mobile phone has not Spotify opened. When I try to click on "fetch devices" nothing happens. The list of devices is empty.

> I guess the reason is that you connect to a device which is not the active one.

How can I set the active device?

**Comment by JasonJunJun** [comment]
You don't have an any available device, how can you listen to music. 😂

You need to open Spotify, and you need to be Spotify Premium in order to listen to the songs in the queue.

See more in [Connect  - Spotify](https://www.spotify.com/is/connect/)

**Comment by abbrechen** [comment]
Oh, ok, haha. Sry then. And thanks for the fast reactions. :)
