### ISSUE TITLE
Todo news functionality idead

### ISSUE THREAD

**Issue by PrincesseLulu** [JMPerez/c#16]
Hi,

For start, thank you for your work.
It's a good app but isn't usable for party.

 _____________
- Because often, only the host have a spotify account, and for the spotify api only need the spotify host to cast the sound.. A lot of app of spotify jukebox just ask for the host spotify account and the guest just send a temporary pseudo. 

- Why not more responsive on mobile device ? I think the most usage on party is on the smartphone's guest.

- And maybe a vote system and host permissions for reject a sound ?
_________________
If you help for the first idea maybe i can help for dev' my other ideas ! I'm to a nodejs dev'.

**Comment by JMPerez** [comment]
Thanks @PrincesseLulu for your great ideas!

I will say they all make sense and would be very useful to improve the project. I haven't spent much time on this lately and the main goal of making it open sourced was to serve to inspire and to show how to use Spotify's Web API.

Feel free to fork the project and implement any suggestions, or send PRs directly to this repo, so I can review.
