### ISSUE TITLE
Audio not working correctly

### ISSUE THREAD

**Issue by bundit** [JMPerez/c#17]
Hi @JMPerez! I really enjoy the idea of this project so thank you for your work! 

Currently, I am having trouble getting the audio to work at all. I can queue a song and have it "play" which shows the progress bar moving from start to finish. Am I missing something? 

Edit: I have tried running it both locally and on the demo herokuapp.

**Comment by JasonJunJun** [comment]
Do you mean you can't hear the audio on the tab?

**Comment by bundit** [comment]
Yes exactly. I am accessing the app through chrome

**Comment by JasonJunJun** [comment]
Duplicate of #14

**Comment by bundit** [comment]
Thanks. Excuse my ignorance
