### ISSUE TITLE
Troubling Building & Deploying

### ISSUE THREAD

**Issue by brandondadam** [JMPerez/c#7]
Hi, if I clone the project npm install, and npm run dev. It works. 

But when I npm run build && npm run start. It fails.

Can you help? 

<img width="1680" alt="screen shot 2018-11-29 at 11 05 27 pm" src="https://user-images.githubusercontent.com/7631485/49269593-5fa1a400-f42b-11e8-827e-81063068dec0.png">

**Comment by brandondadam** [comment]
Yes I have. All is setup correctly, and it works perfectly fine when I run it in dev. For some reason it just won't build to production. I even did a clean clone from this repo to see if it was just my changes, but I did the clone, added my spotify credentials, and the same thing occurred when I tried to build. I'm not sure what the issue is?

**Comment by JMPerez** [comment]
You are right, there seems to be some error. I managed to reproduce it.

Debugging it gets a bit cryptic and there is no `styleId` in the code. It's difficult to pinpoint where this is coming from.

**Comment by brandondadam** [comment]
That styleID was an issue with me. I have no clue how to go about debugging it though. I'll keep trying to debug on my end as well and let you know if I find a fix. Thanks!

**Comment by JMPerez** [comment]
The issue comes from https://github.com/zeit/styled-jsx. If I remove all the styles it works fine.

I'm trying out checking out old versions of the app to determine when it broke.

**Comment by JMPerez** [comment]
@brandondadam I decided to remove preact. I couldn't figure out exactly why it wasn't working properly with styled-jsx in production mode.

**Comment by brandondadam** [comment]
Thanks! It worked.

**Comment by brandondadam** [comment]
Yeah, this project is written in a pretty interesting way, so my friends and I couldn't figure it out. But thanks for taking care of this issue.
