### ISSUE TITLE
a bug in sessionMiddleware.js?

### ISSUE THREAD

**Issue by JasonJunJun** [JMPerez/c#9]
https://github.com/JMPerez/c/blob/fe060c04af46b7cb402c70b193bd03d9171b4bb6/middlewares/sessionMiddleware.js#L46

I think that what you want to do is "when there is no `expiresIn` or `now` > `10 minutes before expiresIn`, you need to refresh token", so the code should be `const needsToUpdate = !expiresIn || expiresIn - 10 * 60 * 1000 < Date.now();`.

Ignore me if I'm wrong.

**Comment by JMPerez** [comment]
I believe they are equivalent. 

If the expiration date is set to a time before now minus 10 minutes? then update

It might be clearer saying 

```js
const diff = expiresIn - Date.now();
if (diff < 10 * 60 * 1000) {
  // update, since we always want to have a token that lasts at least for 10 minutes.
}
```

**Comment by JasonJunJun** [comment]
If `expiresIn` is 5 minutes before now, then `const needsToUpdate = !expiresIn || expiresIn < Date.now() - 10 * 60 * 1000;`  is false, but actually, we should update the token, because the access token is expired.

**Comment by JMPerez** [comment]
True!

I'll merge this.

**Comment by JasonJunJun** [comment]
okay.

**Comment by JasonJunJun** [comment]
#10
